### PR TITLE
Make the repo compatible with cuDF nightly

### PR DESCRIPTION
**Pull request by gaohao95**
This PR is built on top of #39

### CODE REVIEW

**Comment by esoha-nvidia** [comment]
Want to rebase this so that we can see it without the other changes?

**Comment by gaohao95** [comment]
> Want to rebase this so that we can see it without the other changes?

Should be done.

**Comment by esoha-nvidia** [comment]
> > Want to rebase this so that we can see it without the other changes?
> 
> Should be done, although I hope github can automatically reconstruct diff in this case.

Yes, but this way it is easier for me to review it because it has fewer changes, so the job is easier for the reviewer.

**Review by esoha-nvidia — APPROVED** [review]

**Comment by gaohao95** [comment]
> > > Want to rebase this so that we can see it without the other changes?
> > 
> > 
> > Should be done, although I hope github can automatically reconstruct diff in this case.
> 
> Yes, but this way it is easier for me to review it because it has fewer changes, so the job is easier for the reviewer.

Agree. Thanks for reviewing this PR :)

**Pull request merged**
